use_frameworks!

platform :ios, '10.0'

target 'NewDemoProtocolManager_Example' do
  pod 'NewDemoProtocolManager', :path => '../'

  target 'NewDemoProtocolManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
